### ISSUE TITLE
Add Policy ID to Error Message for Non-Compliant Product Versions

### ISSUE THREAD

**Issue by alessandrarota** [opendatamesh-initiative/odm-platform#192]
When registering a new product version that does not comply with the registration policy, the registry returns an error message similar to this one:
![image](https://github.com/user-attachments/assets/afadc8d3-1adf-4764-86a7-169db8a424fa)

It would be useful if the error message also included the ID of the policy that was violated.

Currently, to determine which policy is causing the error, we have to check the logs of different images. Including the policy ID in the error message would simplify this process, allowing us to easily perform a GET request on the specific policy and quickly identify the issue.

**Comment by aliprax** [comment]
Thank you for your suggestion, @alessandrarota. We agree that including the ID of the violated policy in the error message would greatly improve usability by simplifying issue identification.

This enhancement has been added to our development pipeline under ticket code BDMD-3625. The expected delivery date for this update is 24 December 2024.

We’ll update this issue once the feature is implemented and released.
