### ISSUE TITLE
Extend NotificationClient

### ISSUE THREAD

**Issue by mattia155** [opendatamesh-initiative/odm-platform#68]
- Extend MetaServiceClient to map each NotificationController endpoint
- Extend ITs in [odm-platform-up-services-meta-blindata](https://github.com/opendatamesh-initiative/odm-platform-up-services-meta-blindata): add all test scenarios in NotificationIT

**Comment by andrea-gioia** [comment]
Rename MetaServiceClient to NotificationClient
